from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from datetime import datetime


def generate_pdf_report(
    report_text,
    pdf_path,
    summary,
    overall_risk
):

    doc = SimpleDocTemplate(
        pdf_path
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        leading=30,
        spaceAfter=20
    )

    file_style = ParagraphStyle(
        "FileHeading",
        parent=styles["Heading1"],
        fontSize=18,
        leading=22,
        spaceBefore=15,
        spaceAfter=12
    )

    section_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=14,
        leading=18,
        spaceBefore=10,
        spaceAfter=8
    )

    body_style = ParagraphStyle(
        "BodyStyle",
        parent=styles["BodyText"],
        fontSize=11,
        leading=16,
        spaceAfter=5
    )

    elements = []

    # =========================
    # TITLE
    # =========================

    elements.append(
        Paragraph(
            "AI Code Review Report",
            title_style
        )
    )

    elements.append(
        Paragraph(
            f"Generated On: {datetime.now().strftime('%d %B %Y %H:%M')}",
            body_style
        )
    )

    elements.append(
        Spacer(1, 25)
    )

    # =========================
    # SUMMARY DASHBOARD
    # =========================

    file_count = report_text.count(
        "# File Review:"
    )

    bug_count = report_text.count(
        "## Bugs"
    )

    security_count = report_text.count(
        "## Security Issues"
    )

    elements.append(
        Paragraph(
            "Executive Summary",
            file_style
        )
    )

    elements.append(
        Paragraph(
            f"Files Reviewed: {summary['files_reviewed']}",
            body_style
        )
    )

    elements.append(
        Paragraph(
            f"Total Bugs Found: {summary['bugs']}",
            body_style
        )
    )

    elements.append(
        Paragraph(
            f"Total Security Issues Found: {summary['security']}",
            body_style
        )
    )

    elements.append(
        Paragraph(
            f"Total Improvements Suggested: {summary['improvements']}",
            body_style
        )
    )

    elements.append(
        Paragraph(
            f"Overall Risk Level: {overall_risk}",
            body_style
        )
    )

    elements.append(
        Spacer(1, 25)
    )

    # =========================
    # FILE REVIEWS
    # =========================

    for line in report_text.splitlines():

        line = line.strip()

        if not line:
            continue

        if line.startswith("# File Review:"):

            elements.append(
                Spacer(1, 15)
            )

            elements.append(
                Paragraph(
                    line.replace("# ", ""),
                    file_style
                )
            )

        elif line.startswith("##"):

            elements.append(
                Paragraph(
                    line.replace("## ", ""),
                    section_style
                )
            )

        elif line.startswith("*"):

            elements.append(
                Paragraph(
                    f"• {line[1:].strip()}",
                    body_style
                )
            )

        else:

            elements.append(
                Paragraph(
                    line,
                    body_style
                )
            )

        # Divider after improvements section

        if line.startswith("## Improvements"):

            elements.append(
                Spacer(1, 10)
            )

    # =========================
    # FOOTER
    # =========================

    elements.append(
        Spacer(1, 20)
    )

    elements.append(
        Paragraph(
            "______________________________________________",
            body_style
        )
    )

    elements.append(
        Spacer(1, 10)
    )

    elements.append(
        Paragraph(
            "Generated by AI Code Reviewer",
            styles["Italic"]
        )
    )

    doc.build(
        elements
    )

    return pdf_path